// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhqmnwdgswpiefzyeeqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJocW1ud2Rnc3dwaWVmenllZXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTc1ODYsImV4cCI6MjA3MTg3MzU4Nn0.lGRAEW8I5WlD9z0p5vjhKyzx1yar2841bSo9-hEX2ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});